# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
          
    - name: Run Docker container
      run: docker run -d -p 8080:80 helloworld
      id: docker-container

    - name: Install curl in the Docker container
      run: docker exec -it ${{ steps.docker-container.outputs.container_id }} apt-get update && apt-get install -y curl

    - name: Test Docker image
      run: |
        echo "Waiting for the container to start..."
        sleep 10

        echo "Checking HTTP response code..."
        response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
        if [ $response_code -eq 200 ]; then
          echo "Docker container is responding successfully."
        else
          echo "Error: Docker container did not respond as expected. HTTP code: $response_code"
          exit 1
        }

      

