name: Publish Docker image
on:
  release:
    types: [published]
    workflow_dispatch:
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/mathbruuu/day2daytestting:latest
          if [ $? -ne 0 ]; then
            exit 1
          fi
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Déchiffrer la clé privée
        run: |
          echo "${{ secrets.DOCKER_TRUST_PRIVATE_KEY }}" > private_key.key
          echo "${{ secrets.PASSPHRASE }}" > passphrase.txt
          gpg --batch --passphrase-file passphrase.txt --import private_key.key
          rm private_key.key passphrase.txt

      
      - name: Sign Docker image
        run: docker trust sign ghcr.io/mathbruuu/day2daytestting:latest
        
      - name: Push the Docker image
        run: |
          docker push ghcr.io/mathbruuu/day2daytestting:latest
          if [ $? -ne 0 ]; then
            exit 1
          fi
