name: Publish Docker image and sign it
permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  push-to-registry:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    steps:
        - name: Check out the repository
          uses: actions/checkout@v4
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_REPO_LOGIN }}
            password: ${{ secrets.DOCKER_REPO_PASSWORD }}
        - name: Build action image
          # Use any good build command and be sure to tag the image correctly
          run: docker build . --tag mathbruu/day2day:latest
          env:
            IMAGE_TAG: "mathbruu/day2day:latest"

        - name: Sign and push docker image
          uses: sudo-bot/action-docker-sign@latest
          with:
            image-ref: "mathbruu/day2day:latest"
            # Example: 51f9a39f3db4ddaaf9174fca69f41fb01a04a4dfb5125ef115feecb93d19efa6
            private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
            # The contents from: ~/.docker/trust/private/51f9a39f3db4ddaaf9174fca69f41fb01a04a4dfb5125ef115feecb93d19efa6.key)
            private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
            # Example: myPassw0rdChangeMeReplaceMe
            private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}
